### PR TITLE
Student UI: Print improvements

### PR DESCRIPTION
**Pull request by Coenego**
* [ ] Remove current day styling from print views (browser setting)
* [x] Remove scroll bar?
* [ ] Investigate: Can the events be made smaller or use X events more... in month view (n/a)
* [ ] Can we match the title font family to Myriad Pro (n/a)

my_timetable_march_2015
?

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Issue remaining: Week, month and day view all have issues with the height of the calendar container.

**Comment by bp323** [comment]
Back to @Coenego for followup

**Comment by bp323** [comment]
This causes an issue in the 'My agenda' view where content is pushed down the page quite a bit.

**Comment by Coenego** [comment]
I assume this was good to go then? I couldn't reproduce the issue when printing the calendar.. ( @bp323 )

**Comment by bp323** [comment]
I'm still seeing these calendar issues, I think it has to do with resolution but I have it in latest Chrome in pretty much any resolution.

screen shot 2015-04-23 at 12 38 54

**Comment by bp323** [comment]
I'd like to get this fixed as it's a step back from what it was before.

**Comment by bp323** [comment]
Followed up and merged into master

**Pull request closed without merging**
