### PR TITLE
Add the event type icon to the event popover

### PR DESCRIPTION
**Pull request by Coenego**
screen shot 2015-02-25 at 15 44 21

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review.

Warning: this cannot be merged until https://github.com/fronteerio/grasshopper/tree/events-type has been merged into master

**Comment by bp323** [comment]
I'll do an initial review and hold off merging

**Comment by bp323** [comment]
All except one thing looks good. When looking at the calendar in the admin UI the lecture type icon doesn't show up properly:

screen shot 2015-03-12 at 11 50 18

**Comment by bp323** [comment]
Looks like this also happens in the student UI when no lecture type is set to the event:

screen shot 2015-03-12 at 11 51 55

**Comment by bp323** [comment]
Back to @Coenego for followup

**Comment by Coenego** [comment]
Issue solved. Reassigning to @bp323

**Comment by Coenego** [comment]
**NOTE**: Before merging, the back-end repository in the Travis file needs to be reverted back to `CUL-DigitalServices/grasshopper:master` when https://github.com/fronteerio/grasshopper/tree/events-type is merged.

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Verified and merged.

**Pull request merged**
