### PR TITLE
Date issue when adding a new event

### PR DESCRIPTION
**Pull request by Coenego**
When adding a new event and editing the date the following error pops up:

```java
Uncaught Error: A valid date should be providedgh.api.util.js:180 
exports.fixDateToGMTgh.datepicker.js:147 
setCalendarDategh.datepicker.js:215 
_.defer.$trigger.clickover.onShownbootstrapx-clickover.js:105 
$.extend.clickeryrequire-jquery.js:2532 
jQuery.extend.proxy.proxyrequire-jquery.js:6450 
jQuery.event.dispatchrequire-jquery.js:6136 
jQuery.event.add.elemData.handlerequire-jquery.js:6365 
jQuery.event.triggerrequire-jquery.js:6916 
(anonymous function)require-jquery.js:2394 
jQuery.extend.eachrequire-jquery.js:2159 
jQuery.fn.jQuery.eachrequire-jquery.js:6915 
jQuery.fn.extend.triggergh.datepicker.js:221 
(anonymous function)lodash.js:5495 (anonymous function)
```

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Fix looks good, one thing though:

- When adding a new event row, the 'gh-new-event-row' class should be applied after a date is picked.

**Comment by bp323** [comment]
Looks good, I'll wait for the build to succeed before merging.

**Comment by bp323** [comment]
Verified and merged

**Pull request merged**
