### PR TITLE
Minor batch edit component styling adjustments

### PR DESCRIPTION
**Pull request by Coenego**
* [x] On #gh-batch-edit-container: padding: 30px 30px 5px;
* [x] On #gh-batch-edit-container h1: margin-bottom: 25px;
* [x] Set border colors to #171717
* [x] Set border-radius on all elements to 5px
* [x] Not sure if this is possible: increase placeholder text color a bit (more darker, just a tiny bit)

timetable_administration

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Looks good, one comment left. Could you remove the border radius from the inner input field for lecturers?
screen shot 2015-04-02 at 11 35 36

**Comment by bp323** [comment]
Back to @Coenego for followup

**Comment by Coenego** [comment]
Reassigning to @bp323 for review after follow-up

**Comment by bp323** [comment]
Verified and merged.

**Pull request merged**
