### PR TITLE
Tests fail after merging with latest back-end master

### PR DESCRIPTION
**Pull request by Coenego**
The unit tests seem to be failing after merging with the latest master

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Still a few issues left with the tests. Back to @Coenego

**Comment by Coenego** [comment]
Reassigning to @bp323

**Comment by Coenego** [comment]
Normal test users are now created using the tenant UI for the Casper tests. Assigning to @bp323 for review.

**Comment by bp323** [comment]
Verified and merged!

**Pull request merged**
