### PR TITLE
Add tenants/apps using the 'enter' key

### PR DESCRIPTION
**Pull request by bp323**
Adding tenants and apps should be possible using the 'enter' key besides using the submit button in the global admin.

### CODE REVIEW

**Comment by bp323** [comment]
Reassigning to @Coenego for review.

**Comment by Coenego** [comment]
Code looks good, just some thoughts about the functional part:

- Can you add a return on this line: https://github.com/CUL-DigitalServices/grasshopper-ui/pull/100/files#diff-2fe41f84c9ad6d4947aa7f1bc5554d93R168 ? The loop would continue otherwise when an error occurs.

- Should we have a button to delete global administrators, apps... as well?

**Comment by Coenego** [comment]
Review done, back to @bp323

**Comment by bp323** [comment]
I've added the return when there's an error.

We should definitely have those buttons, but I was going to incorporate them as part of another ticket (https://github.com/CUL-DigitalServices/grasshopper-ui/issues/347) as this is getting quite big already.

**Comment by bp323** [comment]
Back to @Coenego for review.

**Pull request merged**
