### PR TITLE
Only allow `data` as main parameter in templates

### PR DESCRIPTION
**Pull request by Coenego**
We should only pass in a `data` parameter which contains all the template data.

screen shot 2015-02-27 at 07 29 42

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Issue in batch edit when selecting a term: `Uncaught ReferenceError: daysInUse is not defined`

**Comment by bp323** [comment]
Code looks good, one issue to follow up on. Back to @Coenego

**Comment by Coenego** [comment]
Back to @bp323 for review after follow-up

**Comment by bp323** [comment]
Noticed an issue with the borrowing modal:

screen shot 2015-03-23 at 16 43 24

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Verified and merged

**Pull request merged**
