### PR TITLE
Added button to open an application

### PR DESCRIPTION
**Pull request by Coenego**

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Few functional remarks:

- Update should be the last button in the row
- The different buttons should be split up in multiple td and th elements so they make better use of the available space.

Back to @Coenego for follow-up

**Comment by Coenego** [comment]
Assigning to @bp323 for review after follow-up

**Comment by bp323** [comment]
Verified and merged.

**Pull request merged**
