### PR TITLE
Batch-edit autosuggest styling

### PR DESCRIPTION
**Pull request by Coenego**
Bringing the autosuggest component into line with the admin UI

### CODE REVIEW

**Comment by Coenego** [comment]
Up to @simong for review

**Comment by simong** [comment]
Should admins be able to enter freeform text?

**Comment by simong** [comment]
Rather than threedotting the author's list in view mode, could you show all lecturers? It'll look a bit less streamlined, but hopefully with the collapsable sidebar and sufficient padding, it'll still look nice

**Comment by Coenego** [comment]
@simong : 

1. Yes, because not all lecturers will have an CRSID.
2. It won't make any difference when the sidebar is collapsed since the column has a fixed width. (It's a pain to align them with the batch edit header fields otherwise).

**Comment by Coenego** [comment]
Increased col-width for lecturers in https://github.com/CUL-DigitalServices/grasshopper-ui/pull/483. Back to @simong

**Pull request merged**
