### PR TITLE
Stylesheets should be concatenated

### PR DESCRIPTION
**Pull request by Coenego**
To reduce the number of requests, we should concatenate the CSS files. We can either do this in a build step using Grunt or use Sass (Compass) to process the files before building.

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Issue remaining: the error pages need to be updated as well.

**Comment by bp323** [comment]
Issue remaining: the `/admin/users/` pages seem to be missing some styles (see how the Autosuggest displays, for example)

**Comment by Coenego** [comment]
Back to @bp323 for review after follow-up

**Comment by bp323** [comment]
Verified and merged, nice work!

**Pull request merged**
