### PR TITLE
Separate util files from controllers

### PR DESCRIPTION
**Pull request by Coenego**
The utility files should be split up from the controllers, instead of having `/shared/gh/js/controllers/gh.api.util.js`.

```
|-- constants
|-- controllers
|-- utils
   |-- gh.utils.js
   |-- gh.utils.time.js
   |-- gh.utils.templates.js
   |-- ...
|-- views
```

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
I think I'll leave this one hanging until all PRs have been merged.

**Comment by bp323** [comment]
Can you take a look at the merge conflict?

**Comment by Coenego** [comment]
Fixed merge conflict. Reassigning to @bp323

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by Coenego** [comment]
Fixed some minor bugs. Back to @bp323

**Comment by bp323** [comment]
Verified and merged

**Pull request merged**
