### PR TITLE
Fade out success and failure colorisation after update in batch edit

### PR DESCRIPTION
**Pull request by bp323**
The success en failure colorisation should fade out after a while when updates have been persisted.

### CODE REVIEW

**Comment by bp323** [comment]
Reassigning to @Coenego for review.

**Comment by Coenego** [comment]
I wonder if when updating a row failed should result in putting the row back into an `active` (grey) state? Currently, there is no indication which rows failed after the failure colorisation faded out.

**Comment by Coenego** [comment]
Left a question for @bp323

**Comment by bp323** [comment]
Good point, I'll make some changes.

**Comment by bp323** [comment]
Fixed the remaining issue, back to @Coenego

**Pull request merged**
