### PR TITLE
Improve student UI list scrolling behaviour

### PR DESCRIPTION
**Pull request by Coenego**
The scroll bar interferes quite a bit with the main journey of adding items to your calendar, so we should make that better a little bit by eliminating the middle scroll bar if we can.

my_timetable_mar_26_ _apr_1__2015

One idea to do this is here:
https://drive.google.com/open?id=0B2lp5OAL6DPFQk51UDRLZlhpSE0&authuser=0

### CODE REVIEW

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
This causes an issue in the 'My agenda' view where content is pushed down the page quite a bit.

**Comment by bp323** [comment]
Back to @Coenego for followup

**Comment by Coenego** [comment]
Assigning to @bp323 for review

**Comment by bp323** [comment]
Verified and merged.

**Pull request merged**
